### ISSUE TITLE
Agregar la página de perfil, las medallas y el semaforo

### ISSUE THREAD

**Issue by baesparza** [Binnarium/mobile-2222#199]

**Comment by baesparza** [comment]
acepte los cambios que subiste, pero se pueden mejorar algunas cosas
- Tenemos varios widgets en el mismo archivo, esos podemos moverlos a archivos contiguios en la misma carpeta de widgets
- podemos encapsular un widget que sea avatar con un flag y ahi vive la logica de cambiar el logo, porque sino la logica esta en el screen.
- Corriamos los separadores de las targetas

**Comment by Danthology96** [comment]
Perfecto Bruno, justo le hice el pull request para que me ayudes viendo qué
se podía mejorar, hoy en la tarde hago esas mejoras 👌
